core: Fix use of hostname in startup / management scripts
HOSTNAME is no longer used directly to address the node. Instead, an
internal NODEHOST variable is used which is equal to the system
hostname ($HOSTNAME).

However, in the case of running with -sname (the default), only the
first part of $HOSTNAME (everything before the first dot) is used as
the node host.

Additionally, added some checks to zotonic start/stop/debug to print a
human-readable explanation when attempting to start the same Zotonic
node twice or trying to stop Zotonic when it is not running.

diff --git a/src/scripts/helpers/zotonic_setup b/src/scripts/helpers/zotonic_setup
--- a/src/scripts/helpers/zotonic_setup
+++ b/src/scripts/helpers/zotonic_setup
@@ -25,6 +25,17 @@ function require_zotonic_running {
 }
 export -f require_zotonic_running
 
+function require_zotonic_not_running {
+    PONG=$($ZOTONIC_CALL -a "zotonic ping" 2>&1)
+    if [ "$PONG" = "pong" ]; then
+        echo "Zotonic is already running as $NODENAME@$NODEHOST." 1>&2
+        echo "You cannot start two Zotonic instances with the same node name." 1>&2
+        echo 1>&2
+        exit 1
+    fi
+}
+export -f require_zotonic_not_running
+
 export ZOTONIC_BIN=${ZOTONIC_BIN:=$ZOTONIC/bin}
 export SITES=${SITES:=$ZOTONIC/priv/sites}
 
@@ -61,7 +72,6 @@ export PA=${PA:="$ZOTONIC/ebin $ZOTONIC/deps/*/ebin $ZOTONIC/modules/*/deps/*/eb
 DISTRIBUTED_DETECTED=$(ps u |grep beam.smp|grep $NODENAME@$HOSTNAME|grep \\-name>/dev/null&&echo true||echo false)
 export ZOTONIC_DISTRIBUTED=${ZOTONIC_DISTRIBUTED:=$DISTRIBUTED_DETECTED}
 
-
 # The name of the Erlang node, this must be unique on your host. ($SNAME is for b.c.)
 export NODENAME=${NODENAME:=${SNAME:=zotonic001}}
 
@@ -77,21 +87,19 @@ if [ "$ZOTONIC_DISTRIBUTED" = "true" ]; then
         exit 1
     fi
     export NAME_ARG=-name
-    export NODE="$NODENAME@$HOSTNAME"
+    export NODEHOST="$HOSTNAME"
 else
+    # Only use the part for the dot of the hostname.
+    export NODEHOST=`echo $HOSTNAME|sed 's/\..*//'`
     export NAME_ARG=-sname
-    export NODE="$NODENAME"
 fi
-
-# Hostname to the fully qualified domain name of your host, or leave it as localhost.
-export HOSTNAME=${HOSTNAME:=localhost}
 
 # The filename where zotonic writes its unix process Id to, for monitoring applications.
 export ZOTONIC_PIDFILE=$ZOTONIC/zotonic.pid
 
 # Locate the path to the erl_call binary
 ERL_CALL=$($ERL -noshell -noinput  -eval "io:format(\"~s\", [code:priv_dir(erl_interface)])" -s erlang halt|sed 's~priv$~bin/erl_call~')
-export ZOTONIC_CALL="$ERL_CALL $NAME_ARG $NODENAME@$HOSTNAME"
+export ZOTONIC_CALL="$ERL_CALL $NAME_ARG $NODENAME@$NODEHOST"
 
 # Make sure the erlang.config file exists
 if [ ! -e "$ZOTONIC/priv/erlang.config" -a -e "$ZOTONIC/priv/erlang.config.in" ]; then
