Support for returning exit codes from zotonic subcommands. Needed for unit tests to report its error status.

diff --git a/src/scripts/zotonic-runtests b/src/scripts/zotonic-runtests
--- a/src/scripts/zotonic-runtests
+++ b/src/scripts/zotonic-runtests
@@ -16,6 +16,8 @@
 
 cd $ZOTONIC
 
+set -e
+
 SNAME="testsandbox"
 ZOTONIC_PORT=8040
 
@@ -37,10 +39,7 @@ erlydtl)
     for MODULE in $MODULES; do ALL="$ALL,$MODULE"; done
     ALL=`echo $ALL|sed 's/^,//'`
 
-    #exec erl -noshell -pa ebin -eval "eunit:test([$ALL],[verbose]),init:stop()"
-
-    echo $ALL
-    $ERL +P 10000000 +K true -pa $PA -name $SNAME@$HOSTNAME -boot start_sasl -sasl errlog_type error -s zotonic -eval "timer:sleep(3000),eunit:test([$ALL],[]),init:stop()"
+    $ERL +P 10000000 +K true -pa $PA -name $SNAME@$HOSTNAME -boot start_sasl -sasl errlog_type error -s zotonic -eval "timer:sleep(3000),init:stop(case eunit:test([$ALL],[]) of error -> 1; ok -> 0 end)"
 ;;
 esac
 
