Tweak the zotonic-addsite command
- require the site name to be reachable by ping
- require zotonic to be started
- build the site and start it through erl_call

diff --git a/src/scripts/zotonic-addsite b/src/scripts/zotonic-addsite
--- a/src/scripts/zotonic-addsite
+++ b/src/scripts/zotonic-addsite
@@ -81,10 +81,19 @@ function do_addsite {
     fi
 
     # Make the new site
-    make -C $ZOTONIC
+    echo "Building site..."
+    $ZOTONIC_CALL -a "make all [[load]]"  > /dev/null
 
+    URL="http://$SITE:${ZOTONIC_PORT:=8000}/"
+    
+    echo "Starting..."
+    curl -s $URL > /dev/null
+    sleep 1
+    
+    $ZOTONIC_CALL -a "z_sites_manager start [$SITE]" > /dev/null
+    
     echo
-    echo "Added site $SITE. Now start zotonic and go to http://$SITE:${ZOTONIC_PORT:=8000}/ to view it."
+    echo "Added site $SITE. Now start zotonic and go to $URL to view it."
 }
 
 
@@ -95,6 +104,13 @@ function check_options {
 
     if [ -f "$HOME/.zotonic-defaults" ]; then
         source "$HOME/.zotonic-defaults"
+    fi
+
+    $ZOTONIC_CALL -a "zotonic status"  &> /dev/null
+    if [ "$?" != "0" ]; then
+        echo "Zotonic is not running. You need to start zotonic first to use this command."
+        echo
+        exit 1
     fi
 
     # The defaults
@@ -135,6 +151,18 @@ function check_options {
         exit 1
     fi
 
+    if ! ping -c 1 -q $SITE &>/dev/null; then
+
+        echo "$SITE cannot be reached. You should add $SITE to your /etc/hosts file,"
+        echo "otherwise you won't be able to reach it after installing the site."
+        echo "Add the following line to /etc/hosts:"
+        echo
+        echo "127.0.0.1         $SITE"
+        echo
+        exit 1
+    fi
+    
+    
     # allow %%SITE%% syntax in db name and schema
     DBDATABASE=`echo $DBDATABASE|sed "s/%%SITE%%/$SITE/g"`
     DBSCHEMA=`echo $DBSCHEMA|sed "s/%%SITE%%/$SITE/g"`
